<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpressYourself.Application\ExpressYourself.Application.csproj" />
    <ProjectReference Include="..\ExpressYourself.Domain\ExpressYourself.Domain.csproj" />
    <ProjectReference Include="..\ExpressYourself.Infrastructure\ExpressYourself.Infrastructure.csproj" />
  </ItemGroup>

</Project>
