<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9949c36a-0fe5-4537-b10c-74b08efc8d31</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.2" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	    <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
	  <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
	  <PackageReference Include="Microsoft.OpenApi" Version="2.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpressYourself.Application\ExpressYourself.Application.csproj" />
    <ProjectReference Include="..\ExpressYourself.Domain\ExpressYourself.Domain.csproj" />
    <ProjectReference Include="..\ExpressYourself.Gateway\ExpressYourself.Gateway.csproj" />
    <ProjectReference Include="..\ExpressYourself.Infrastructure\ExpressYourself.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
